CREATE TABLE IF NOT EXISTS  providers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lifetime VARCHAR(255) NOT NULL
);

INSERT IGNORE INTO providers (id, name, lifetime)
    VALUES (1, 'REFRESH', '1h');

CREATE TABLE IF NOT EXISTS  users (
    id VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS  sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    providerId INT NOT NULL,
    fingerprint VARCHAR(255) NOT NULL,
    expiresAt TIMESTAMP NOT NULL,
    userId VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    FOREIGN KEY (providerId) REFERENCES providers(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    extension VARCHAR(255) NOT NULL,
    mimeType VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    path VARCHAR(500) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    userId VARCHAR(255) NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
)
